### PR TITLE
Makes summary optional for toVEVENT

### LINKED ISSUE #23: Summary is mandatory
Hey,
I am currently creating TypeScript typings for this module, but it seems according to line https://github.com/TimDaub/simple-caldav/blob/29a11a4609ad6e547255cb5d75aa78196914b4e8/src/index.js#L193
that you have made the summary a required field while it is optional in the spec. And it seems except for this line it is optional elsewhere in your code.

### PR DESCRIPTION
**Pull request by chaptergy**
Would fix #23

### CODE REVIEW

**Comment by chaptergy** [comment]
The pipeline failing does not seem to have anything to do with the changes. I have marked this PR as a draft anyways.

**Comment by TimDaub** [comment]
Thanks for this PR.

> The pipeline failing does not seem to have anything to do with the changes.

Yes. #25. I'll take a look.

**Comment by TimDaub** [comment]
Hey sorry. You probably now got a flurry of notifications. A quick summary of what I think happens. There's #25 that was failing tests for anyone forking simple-caldav as GitHub Actions don't share secrets across forks (e.g. yours).

So I was able to now remove webfactory/ssh-agent@v0.4.1 which should fix the problem. So now we can do either of two things:

- You rebase this PR with the latest master and I merge it when tests pass
- I merge #26 with your commit and we can close this PR.

I'm giving you these options as you said you marked the PR as a draft, so I thought there may be other changes from you. Please let me know what you prefer.

**Comment by chaptergy** [comment]
I have rebased this branch.

**Comment by TimDaub** [comment]
Thanks!

**Pull request merged**
